config/routes.rb
FoodForGive::Application.routes.draw do
  get "about/index"
  
  root :to => 'confessions#new'
  get 'confessions' => 'confessions#index'
  get 'confessions/new' => 'confessions#new'
  post 'confessions' => 'confessions#create'
  post 'payments' => 'payments#create'
  post 'charges' => 'charges#create'
  get 'about' => 'about#index'

 

end

app/models/confession.rb
class Confession < ActiveRecord::Base
  
  #ensure text is not empty
  validates_presence_of :confession_text, :message => "It's empty!  Share at least one thing... "
  
  end

app/models/payment.rb
class Payment < ActiveRecord::Base
  
  #email is mandatory
  validates_presence_of :email
  
  # email should read like an email address; this check isn't exhaustive,
# but it's a good start
  validates_format_of :email, 
    :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i,
    :message => "doesn't look like a proper email address"

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  
  protect_from_forgery with: :exception
  
  
  
#These are helper methods to check if a request comes from mobile and send the user to the mobile view if true
  def check_for_mobile
    session[:mobile_override] = params[:mobile] if params[:mobile]
    prepare_for_mobile if mobile_device?
  end

  def prepare_for_mobile
    prepend_view_path Rails.root + 'app' + 'views_mobile'
  end

  def mobile_device?
    if session[:mobile_override]
      session[:mobile_override] == "1"
    else
      # Season this regexp to taste. I prefer to treat iPad as non-mobile.
      (request.user_agent =~ /Mobile|webOS/) && (request.user_agent !~ /iPad/)
    end
  end
  helper_method :mobile_device?


    end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
before_filter :check_for_mobile
respond_to :html,:js, :json

def new
end

def create
  # Amount in cents

#Validate the amount to ensure it fits in the safe range.
@donation = params[:amount]
if @donation.to_i < 300 then @donation = 300 
end
if @donation.to_i > 500 then @donation = 500
end

  customer = Stripe::Customer.create(
    :card  => params[:stripeToken]
  )
  

  charge = Stripe::Charge.create(
    :customer    => customer.id,
    :amount      => @donation.to_i,
    :description => 'Food for give donation',
    :currency    => 'usd'
  )

  
respond_to do |format|
  #Set flag to allow view of confessions on successful post
  session[:ipayed] = 1
  puts session[:ipayed]
  #Display the thank you message
  format.js 
end

 rescue Stripe::CardError => e
      # The card has been declined or
      # some other error has occured
      flash[:error] = e.message
      render :new
end

  

end

app/controllers/confessions_controller.rb
class ConfessionsController < ApplicationController
  before_action :check_for_mobile, only: [:new, :create]
  before_action :set_confession, only: [:show, :edit, :update, :destroy]
  before_action :check_if_ipayed, only: [:index]
  respond_to :html, :js, :json
 
  # you can disable csrf protection on controller-by-controller basis:
  #skip_before_filter :verify_authenticity_token

  # GET /confessions
  # GET /confessions.json
  def index
    @confessions = Confession.order('created_at DESC').limit(500).page(params[:page])
  end


  # GET /confessions/new
  def new
    puts view_paths
    @confession = Confession.new
  end



  # POST /confessions
  # POST /confessions.json
  def create
    @confession = Confession.new(confession_params)
    

    respond_to do |format|
      if @confession.save
        format.js 
      #  format.html {render :partial => 'show_confession', :content_type => 'text/html', notice: 'Thank you for sharing!  Now absolve yourself and feel better by helping someone else.' }
       # format.json { render json: @confession.to_json, status: :created }
      else
        format.js 
       # format.html { render action: 'new', notice: 'Thank you for sharing!  We could not save your reponse right now, but absolve yourself and feel better by helping someone else.' }
        #format.json { render json: @confession.errors, status: :unprocessable_entity }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_confession
      @confession = Confession.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def confession_params
      params.require(:confession).permit(:confession_text)
    end
    
    def check_if_ipayed
    @ipayed_val = session[:ipayed]
    puts @ipayed_val

      if @ipayed_val == 1
        return true
      else 
        redirect_to root_path
        return false
      end
    end
    

    
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_filter :check_for_mobile
  before_action :set_confession, only: [:show, :edit, :update, :destroy]
  respond_to :html, :js, :json



  # POST /payments
  # POST /payments.json
  
  def create
    @payment = Payment.new(payment_params)

    respond_to do |format|
      if @payment.save
        #Set session value to indicate successful email sharing
        session[:ipayed] = 1
        
        format.js
        #format.html { redirect_to @payment, notice: 'Payment was successfully created.' }
       # format.json { render action: 'show', status: :created, location: @payment }
      else
        format.js
        #format.html { render action: 'new' }
       # format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_params
      params.require(:payment).permit(:email)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  

  
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/confessions_helper.rb
module ConfessionsHelper
  

  
  
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/about/index.html.erb
  
<div id="outer_confessions" class="face">
	
<img src="/assets/cherub1_lg.png" class="about_cherub_1">
<img src="/assets/cherub2_lg.png" class="about_cherub_2">
        <header>
            <h1>
            	<a href="http://www.foodforgive.com"><span><span>Food ForGive<sub>&trade;</sub></span></span></a>
                <span class="end"></span>
                <br class="clear" />
			</h1>
        </header>
        



<div id="main_confessions">





<div class="about_column_outer_right">
<div class ="about_column">
<img src = "assets/cherub1.png">
<h5>Rodney Hom - Cofounder of Food ForGive</h5>
<p>Rodney is an Art Director/UX Designer. His food confession is that he likes Wedding Cake, 
	mostly because it's so beautiful and it represents so much happiness, love and hope which is why he 
	thinks it may be so delicious. He also loves film and has won a Student Academy Award. Rodney is very single.
</p>
</div>
</div>

  
    
<div class="about_column_outer_left"> 
<div class ="about_column"> 
<img src = "assets/cherub1.png"> 
<h5>Ryan Handerhan - Cofounder of Food ForGive</h5>
<p>Ryan is a Software Engineer. His food confession is that he likes very cheesy nachos, 
	mostly because he’s never not had fun when cheesy nachos are involved. He also loves to sing broadway 
	showtunes while accompanying himself on the piano. Ryan is very single.</p>
</div>

</div>



<div class="about_column_outer_left">
<div class ="about_column">
<img src = "assets/cherub1.png">
<h5>Raymond Heredia - The Original, Super-fab, Web Developer of Food ForGive</h5>
<p>Raymond is a Web Developer.  His food confession is that he likes pistachio frozen yogurt with
	 cheesecake bites on top, mostly because he crack is too expensive (and whack).  He also loves listening to Yoko Ono.  
	 Raymond is very single.</p></div>
</div>	

<br>
<br>
<br>

 <%= link_to '<span id="confess_submit">New Confession</span>'.html_safe, root_path %>
<br>
<br>

</div>
</div>
  
<!-- Footer -->

<footer>
        
        
        <%= link_to '<h3>RH&amp;RH</h3>' .html_safe, about_path %>
        <div>
            <h4>Trademarks</h4>
            <p>Food Forgive are trademarks owned by RH&amp;RH. Such trademarks may not be used in connection with any products or services that are not controlled by RH&amp;RH, or in any manner that is likely to cause confusion among customers, or in any manner that disparages or discredits RH&amp;RH or FoodForGive.com.</p>
        </div>
        <div>
            <h4>Liability Disclaimer</h4>
            <p>RH&amp;RH makes no representations or warranties of any kind, express or implied, as to the operation of the site, the information, content, materials or products included on this site. RH&amp;RH will not be liable for any damages arising from use of this site. Ultimately, all readings and advice arising from use of this site are understood to be for entertainment purposes only.</p>
			
        </div>
        <br class="clear" />
	
</footer>

app/views/charges/create.js.erb
$('#magic-fail').html("");
var responses = new Array();
responses[0] = "Thanks, you're a doll!";
responses[1] = "Feel good!  You have helped another.";
responses[2] = "What a kind donation, thank you.";


$('#magic-response').html("");
$('#magic-response').append("<%= escape_javascript(render(:partial => 'confessions/thankyou')).html_safe %>");
$('#Random_Answer').append(responses[Math.floor(Math.random()*responses.length)]);

app/views/confessions/_form.html.erb
<%= form_for(@confession, remote: true) do |f| %>
  <% if @confession.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@confession.errors.count, "error") %> - Sorry!  This made the confession not record.  The Food ForGive team will be right on it, so come back soon!</h2>

      <ul>
      <% @confession.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :confession_text, 'Share your latest guilty food-pleasure, and find your forgiveness...' %><br>
    <%= f.text_field :confession_text, :id => "confess_text_field" %>
  </div>
  <div class="actions", id="submit_confession">
    <%= f.submit "Forgive Yourself", :id => "confess_submit" %>
  </div>
  
  <div id="magic-response"></div>
  


<% end %>

app/views/confessions/_show_confession.html.erb
<div id="magic_response_inner">
  <p id="Random_Answer"></p>
  <p><div id="tiny-response">(two snaps and a hey)</div>Peace! You’re forgiven.</p>
  <div id="amount-response"><br><p>Giving is part of ForGiving.</p><p>Please donate $<span id="donate-amount"></span> to a foodbank of your choice.</p>

          
  </div>

  <br>
  

 <%= form_tag(charges_path, remote: true) do %>
  
  
      <span id="pay_submit">Give to ForGive!</span>
          

 	 <script>
    var handler = StripeCheckout.configure({
    key: "<%= Rails.configuration.stripe[:publishable_key] %>",
    image: 'assets/cherub1.png',
    token: function(token, args) {
      // Use the token to create the charge with a server-side script.
      var tokenInput = $("<input type=hidden name=stripeToken />").val(token.id);
  	  var amountInput = $("<input type=hidden name=amount />").val($to_pay_amount);
  	  var authenticityToken =$("<input type=hidden value=<%= form_authenticity_token() %> name=authenticity_token />")
      $("form").append(tokenInput).append(amountInput).append(authenticityToken).trigger('submit.rails');
    }
  });

  document.getElementById('pay_submit').addEventListener('click', function(e) {
    // Open Checkout with further options
    handler.open({
      name: 'Food ForGive',
      description: 'Donation to a local Foodbank',
      amount: $to_pay_amount
    });
    e.preventDefault();
  });
          </script>



 <% end %>
</div>

app/views/confessions/edit.html.erb
<h1>Editing confession</h1>

<%= render 'form' %>

<%= link_to 'Show', @confession %> |
<%= link_to 'Back', confessions_path %>

app/views/confessions/new.html.erb

<div id="cherub1" class="cherub"></div>
<div id="cherub2" class="cherub"></div>

<div class="wrapper">
<span class="face">
	<span class="limiter">
        <header>
            <h1>
            	<a href="http://www.foodforgive.com"><span><span>Food ForGive<sub>&trade;</sub></span></span></a>
                <span class="end"></span>
                <br class="clear" />
			</h1>
        </header>
        
        <section class="mast">
            <div class="mast_inner">
            	
	    <%= form_for(@confession, remote: true, :html => {:id => "form_bg"}) do |f| %>
 	 	<% if @confession.errors.any? %>
   	 	<div id="error_explanation">
      	<h2><%= pluralize(@confession.errors.count, "error") %> - Sorry!  This made the confession not record.  The Food ForGive team will be right on it, so come back soon!</h2>

     	 <ul>
      	<% @confession.errors.full_messages.each do |msg| %>
      	  <li><%= msg %></li>
      	<% end %>
     	 </ul>
    	</div>
  		<% end %>
		
	     
	   
	 
	     
	     <div id="magic-response">
	     	

	     	
	     <!--<p id="tiny-response">What do you feel guilty for eating? Come on, it's ok...</p> <br>-->

	     <div id="confess_field" class="field"> <%= f.text_field :confession_text, 	     						

	     						:value => "", 
	     						:placeholder => "Please type your food confession here...",
	     						:style => "text-align: Center",
	     						:id => "confess_text_field"  %> </div>
	     <br>

         <div class="actions" id="submit_confession">
	     <%= f.submit "Forgive Yourself", :id => "confess_submit" %>
	     </div>
	       
	     </div>
	    
	     <br>
	     
	     <div id="magic-fail"></div> 
	  
	     	      	
	     <!-- <div id="u3743_clip">
	      <div class="actions" id="submit_confession">
	           <%= f.submit "Forgive Yourself", :id => "confess_submit" %>
	       </div>
	       <img class="position_content" id="u3743_img" src="/assets/pink%20button.png" alt="" width="80" height="21"/>	       
	     </div>-->
                           
                    <ul class="social">
            			<li><a href="http://www.facebook.com/foodforgive" title="Find Food ForGive on Facebook" class="facebook"><span>Facebook</span></a></li>
            			<li><a href="http://www.twitter.com/foodforgive" title="Follow ForGive on Twitter" class="twitter"><span>Twitter</span></a></li>
            			<li><a href="http://www.pinterest.com/foodforgive" title="Visit the Food ForGive Pinterest Board" class="pinterest"><span>Pinterest</span></a></li>
            			<li><a href="" title="Join the Food ForGive Google+ Circle" class="google"><span>Google+</span></a></li>
            		</ul>
     <% end %>
                    
                    

                
                <br class="clear" />
            </div>
        </section>
    </span><!-- /.limiter -->
</span>
<section class="info">
    <span class="layer">

                <span class="limiter doubleblock1">
				<span class="TL">
				<span class="TR">
				<span class="BR">
				<span class="BL">
						<span class="textParent">
						<h2><span>About</span>Food ForGive<sub>&trade;</sub></h2>
							<p class="jist">Giving is part of ForGiving.</p>
							<p>Food ForGive can forgive any kind of food transgressions, lapses in judgment, or moments of bacchanalian food insanity. Our Confession Cherubs<sub>&trade;</sub> lift your confessions to the Divine and offer encouragement so that you can declare, &quot;I'm moving on, mmm--kay.&quot;</p>
							<p>In the near future, Food ForGive hopes to provide options for you to donate a few dollars to a local food bank. The ultimate, morale-boosting goal of Food ForGive is not only to provide food forgiveness, but also to provide food for give to people and kids in need. Can we get two snaps and a hey?</p>
							<p>Thank you. Peace! And Love.</p>
						
						</span><!-- /.textParent -->
				</span><!-- /.BL -->		
				</span><!-- /.BR -->		
				</span><!-- /.TR -->		
				</span><!-- /.TL -->
                </span><!-- /.limiter .doubleblock-->

    </span><!-- /.layer -->
				<ul class="social">
					<li><a href="http://www.facebook.com/foodforgive" title="Find Food ForGive on Facebook" class="facebook"><span>Facebook</span></a></li>
					<li><a href="http://www.twitter.com/foodforgive" title="Follow ForGive on Twitter" class="twitter"><span>Twitter</span></a></li>
					<li><a href="http://www.pinterest.com/foodforgive" title="Visit the Food ForGive Pinterest Board" class="pinterest"><span>Pinterest</span></a></li>
					<li><a href="" title="Join the Food ForGive Google+ Circle" class="google"><span>Google+</span></a></li>
				</ul>
</section>

<a name="email_form"></a>
<section class="aux">
	<div class="ornamentA"></div>
	<span class="limiter doubleblock2">
        <span class="textParent">
        	<h2><span>Contact</span>Food ForGive<sub>&trade;</sub></h2>
            <p class="jist">You are Super Fun <br>for scrolling all the way down here.</p>
            <p>Because giving is forgiving, Food ForGive hopes to partner with a food bank so that you can have the option of donating a few dollars after your confession. Let's keep in touch because we want you to help us celebrate when that happens &ndash; and no, we're not going to give away your private info because that's no fun at all. Two snaps and a hey. See you soon!</p>
           
               <%=render '/payments/form', :@payment => Payment.new %>
<br>

<div id="payment-text">	
<div id="payment-response">
	</div>
	</div>
		
        </span><!-- /.aux -->
    </span><!-- /.limiter -->
		<ul class="social">
            <li><a href="http://www.facebook.com/foodforgive" title="Find Food ForGive on Facebook" class="facebook"><span>Facebook</span></a></li>
            <li><a href="http://www.twitter.com/foodforgive" title="Follow ForGive on Twitter" class="twitter"><span>Twitter</span></a></li>
            <li><a href="http://www.pinterest.com/foodforgive" title="Visit the Food ForGive Pinterest Board" class="pinterest"><span>Pinterest</span></a></li>
            <li><a href="" title="Join the Food ForGive Google+ Circle" class="google"><span>Google+</span></a></li>
        </ul>
		<div class="ornamentB"></div>
		<div class="ornamentC"></div>
		<div class="ornamentC"></div>
</section>


<footer>
        
        
        <%= link_to '<h3>RH&amp;RH</h3>' .html_safe, about_path %>
        <div>
            <h4>Trademarks</h4>
            <p>Food Forgive are trademarks owned by RH&amp;RH. Such trademarks may not be used in connection with any products or services that are not controlled by RH&amp;RH, or in any manner that is likely to cause confusion among customers, or in any manner that disparages or discredits RH&amp;RH or FoodForGive.com.</p>
        </div>
        <div>
            <h4>Liability Disclaimer</h4>
            <p>RH&amp;RH makes no representations or warranties of any kind, express or implied, as to the operation of the site, the information, content, materials or products included on this site. RH&amp;RH will not be liable for any damages arising from use of this site. Ultimately, all readings and advice arising from use of this site are understood to be for entertainment purposes only.</p>
			
        </div>
        <br class="clear" />
	
</footer>
	<div class="ornamentD"></div>
	<br class="clear" />
</div><!-- /.wrapper -->
<script>

/*Cherub Animations*/
 

$(document).ready(function(){
    var boxpos = 40;
    var last_scroll = 0;
    $("#cherub1").css("left", boxpos);
    $("#cherub2").css("right", boxpos);

    $(window).scroll(function(){
    	//Set the current scroll position
        var pos = $(document).scrollTop();
        if(pos > last_scroll){
        	//We are scrolling down!
            boxpos = boxpos-2;
            $("#cherub1").css("left", boxpos);
            $("#cherub2").css("right", boxpos);
           }
         else
         {
        	//We are going up!
        	boxpos = boxpos+2;
            $("#cherub1").css("left", boxpos);
            $("#cherub2").css("right", boxpos);
         }
      //Update the scroll position
      last_scroll = pos;

    });
});

</script>












app/views/confessions/new.js.erb
$("magic_response").update("<%= escape_javascript(render(@confession))%>");
$("magic_response").append("<p>You are forgiven!</p>");

app/views/confessions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Confession text:</strong>
  <%= @confession.confession_text %>
</p>

<%= link_to 'Edit', edit_confession_path(@confession) %> |
<%= link_to 'Back', confessions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html class="html">
<head>
  <title>FoodForGive</title>
  <meta http-equiv="Content-type" content="text/html;charset=UTF-8"/>
  <meta name="generator" content="7.1.329.244"/>
  
  <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
  <meta name="viewport" content="width=device-width">
  <%= csrf_meta_tags %>
  

  <!--<%= javascript_include_tag 'jquery_ujs' %>-->
  <%= javascript_include_tag 'application'%>
 
 
<!--<link rel="stylesheet" type="text/css" href="/assets/site_global.css?417434784"/>
<link rel="stylesheet" type="text/css" href="/assets/index.css?4053720094" id="pagesheet"/>-->
<link rel="apple-touch-icon-precomposed" sizes="114x114" href="assets/images/apple-touch-icon-114x114-precomposed.png">
<link rel="apple-touch-icon-precomposed" sizes="72x72" href="assets/images/apple-touch-icon-72x72-precomposed.png">
<link rel="apple-touch-icon-precomposed" href="assets/images/apple-touch-icon-57x57-precomposed.png">
<link type="text/css" rel="stylesheet" href="assets/cssreset.css" />
<link type="text/css" rel="stylesheet" href="assets/bad_toothache.css" />
<link type="text/css" rel="stylesheet" href="assets/toothache.css" />
<script type="text/javascript" src="assets/javascripts/scripts/modernizr-2.5.3.min.js"></script>
<!--[if lt IE 9]>
<script type="text/javascript" src="assets/javascripts/scripts/html5shiv.min.js"></script>
<![endif]-->

  <script type="text/javascript">
   document.documentElement.className += ' js';
var __adobewebfontsappname__ = "muse";
</script>
  <!-- JS includes -->
  <script type="text/javascript">
   document.write('\x3Cscript src="' + (document.location.protocol == 'https:' ? 'https:' : 'http:') + '//webfonts.creativecloud.com/linden-hill:n4:all;bubblegum-sans:n4:all;henny-penny:n4:all.js" type="text/javascript">\x3C/script>');
</script>

<script src="https://checkout.stripe.com/checkout.js"></script>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-49511107-1', 'foodforgive.com');
  ga('send', 'pageview');

</script>
</head>
<body> 


<%= yield %>



</body>
</html>

app/views/payments/_form.html.erb
<%= form_for(@payment, remote: true) do |f| %>
  <% if @payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payment.errors.count, "error") %> prohibited this e-mail from being saved:</h2>

      <ul>
      <% @payment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  

<div id="payment-text">
  <div id="confess_field" class="field">
    <%= f.text_field :email, 
    	:id => "payment_text_field",
    	:value => "", 
	    :placeholder => "Please type your email address here...",
	    :style => "text-align: Center"
	     					 %>
  </div>
  <br>
  <div class="actions" id="submit_confession">
    <%= f.submit "Sign-Up!", :id => "confess_submit" %>
  </div>
  </div>
<% end %>

app/views/payments/create.js.erb
  var emailReg = /^([\w-\.]+@([\w-]+\.)+[\w-]{2,4})?$/;
  
  if( !emailReg.test( $('#payment_text_field').val() ) ) {
     $('#payment-response').html("<p>Really?  Please try a legit e-mail...</p>");
  } 
  else if ($('#payment_text_field').val() == "")
  {
  	$('#payment-response').html("<p>Really?  Please try a legit e-mail...</p>");
  }
  else {
    $('#payment-response').html("<p>Thank you, we will be in touch shortly!</p><br>");
	$('#payment-response').append("<%= escape_javascript(link_to 'See what others have confessed...', confessions_path, :id => "confess_submit")  %>");
	new_payment.payment_text_field.value="";
  }

app/views/payments/edit.html.erb
<h1>Editing payment</h1>

<%= render 'form' %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

app/views/payments/index.html.erb
<h1>Listing payments</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= payment.email %></td>
        <td><%= link_to 'Show', payment %></td>
        <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
        <td><%= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment', new_payment_path %>

app/views/payments/new.html.erb
<h1>New payment</h1>

<%= render 'form' %>

<%= link_to 'Back', payments_path %>

app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @payment.email %>
</p>

<%= link_to 'Edit', edit_payment_path(@payment) %> |
<%= link_to 'Back', payments_path %>